# Generated by Django 3.2.8 on 2021-10-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('day1ex1', models.CharField(max_length=50, null=True)),
                ('day1ex1sets', models.IntegerField(null=0)),
                ('day1ex1reps', models.IntegerField(null=0)),
                ('day1ex2', models.CharField(max_length=50, null=True)),
                ('day1ex2reps', models.IntegerField(null=0)),
                ('day1ex2sets', models.IntegerField(null=0)),
                ('day1ex3', models.CharField(max_length=50, null=True)),
                ('day1ex3sets', models.IntegerField(null=0)),
                ('day1ex3reps', models.IntegerField(null=0)),
                ('day1ex4', models.CharField(max_length=50, null=True)),
                ('day1ex4sets', models.IntegerField(null=0)),
                ('day1ex4reps', models.IntegerField(null=0)),
                ('day2ex1', models.CharField(max_length=50, null=True)),
                ('day2ex1sets', models.IntegerField(null=0)),
                ('day2ex1reps', models.IntegerField(null=0)),
                ('day2ex2', models.CharField(max_length=50, null=True)),
                ('day2ex2reps', models.IntegerField(null=0)),
                ('day2ex2sets', models.IntegerField(null=0)),
                ('day2ex3', models.CharField(max_length=50, null=True)),
                ('day2ex3sets', models.IntegerField(null=0)),
                ('day2ex3reps', models.IntegerField(null=0)),
                ('day2ex4', models.CharField(max_length=50, null=True)),
                ('day2ex4sets', models.IntegerField(null=0)),
                ('day2ex4reps', models.IntegerField(null=0)),
                ('day3ex1', models.CharField(max_length=50, null=True)),
                ('day3ex1sets', models.IntegerField(null=0)),
                ('day3ex1reps', models.IntegerField(null=0)),
                ('day3ex2', models.CharField(max_length=50, null=True)),
                ('day3ex2reps', models.IntegerField(null=0)),
                ('day3ex2sets', models.IntegerField(null=0)),
                ('day3ex3', models.CharField(max_length=50, null=True)),
                ('day3ex3sets', models.IntegerField(null=0)),
                ('day3ex3reps', models.IntegerField(null=0)),
                ('day3ex4', models.CharField(max_length=50, null=True)),
                ('day3ex4sets', models.IntegerField(null=0)),
                ('day3ex4reps', models.IntegerField(null=0)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000, null=True)),
                ('comment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applicationFunctions.forumpost')),
            ],
        ),
        migrations.CreateModel(
            name='ClientTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
