# Generated by Django 3.2.8 on 2021-10-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationFunctions', '0002_rename_user_id_forumpost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumreply',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='trainerblog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trainerreview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='user',
        ),
    ]
