# Generated by Django 3.2.8 on 2021-10-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
